//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timerow
    {
        public int ID { get; set; }
        public int TimesheetID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Code { get; set; }
        public string Location { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Sat { get; set; }
        public Nullable<decimal> Sun { get; set; }
        public Nullable<decimal> Mon { get; set; }
        public Nullable<decimal> Tue { get; set; }
        public Nullable<decimal> Wed { get; set; }
        public Nullable<decimal> Thu { get; set; }
        public Nullable<decimal> Fri { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveNotes { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Timesheet Timesheet { get; set; }
    }
}
